### ISSUE TITLE
Asteroid "generate" command/flag

### ISSUE THREAD

**Issue by soap1337** [dailymotion/asteroid#3]
Have you considered doing a form of generating both the server side config and client/peer side configs? So after you do the "add" command, there could maybe be an additional flag that prints output or returns to a file the full client/peer side setup. Btw, this tool looks really slick, I'm excited to try it out!

**Comment by Bencyril** [comment]
Hey @soap1337

Thanks for your input.
It's an interesting point and could be a nice feature, will check it out and see what I can do

Have a good day !

**Comment by Bencyril** [comment]
Hey @soap1337 

I think the PR that has been merged implement what you needed
https://github.com/dailymotion/asteroid/pull/4

Have a good day!

**Comment by soap1337** [comment]
Awesome thanks! I'll be sure to check this out!
