### ISSUE TITLE
More on installing in readme

### ISSUE THREAD

**Issue by emilehickson** [dailymotion/asteroid#6]
Hey I'm quite new to all of this. Can you explain in your Readme how to install Asteroid on a Linux server running Wireguard? Thanks

**Comment by Bencyril** [comment]
hi @emilehickson 
I added more information about building the application with Go in the RADME

Mostly you just have to 
 * Clone the repo on your comoputer
 * Build the app with `go build -o asteroid ./cmd/asteroid`
 * Run the app with `./asteroid` OR copy the binary to `/usr/local/bin`, `chmod ug +x /usr/local/bin/asteroid` and run it like any app

Do you need more information ?

Have a good day!

**Comment by jpptinsley** [comment]
Can you add anything on configuring the server?

**Comment by Bencyril** [comment]
Hi @jpptinsley 

As it's not really the goal of the project, I will redirect you to some documentations that could help you on that:

 - Official: https://www.wireguard.com/quickstart/
 - In French: https://blog.flozz.fr/2020/03/22/wireguard-outils-et-fichiers-de-configuration/
 - Scaleway blog: https://www.scaleway.com/en/docs/installing-wireguard-vpn-linux/

Have a good day!
